### PR TITLE
cleaned up App Docs

### PR DESCRIPTION
**Pull request by dcchivian**

### CODE REVIEW

**Comment by dcchivian** [comment]
note that the GhA unit tests failure is due to it being a fork being merged in as opposed to a branch within kbaseapps. In future I will use branching so GhA should work, but I had an old fork that I was working on from before. I can say that the unit tests are passing against both CI and PROD!

**Review by Tianhao-Gu — APPROVED** [review]
👍  LGTM. only doc changes. It's still good to bump the version in case we cannot release it.

**Comment by dcchivian** [comment]
> 👍 LGTM. only doc changes. It's still good to bump the version in case we cannot release it.

done

**Comment by dcchivian** [comment]
PR approved.  Self-merging to test in beta in Narrative

**Pull request merged**
